site_name: CarbonBalance Docs
theme:
  name: material

extra_css:
  - styles/mermaid.css

markdown_extensions:
- pymdownx.superfences
- pymdownx.details
- pymdownx.tabbed
- admonition
- attr_list
- pymdownx.arithmatex:
    generic: true
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format


extra_javascript:
  - javascripts/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            show_submodules: true
            filters: ["!^_"]
            members_order: source


nav:
  - Home: index.md
  - Reference:
      - API:
          - Projects: reference/api/projects.md
          - Interventions: reference/api/interventions.md
          - Building Metrics: reference/api/building_metrics.md
          - Theme Weights: reference/api/theme_weights.md
          - Admin Users: reference/api/admin_users.md
          - Graphs: reference/api/graphs.md
          - Costing: reference/api/costing.md
          - Ingestion: reference/api/ingestion.md
      - Services:
          - Rules (Metric): reference/services/rules_metric.md
          - Rules (Intervention): reference/services/rules_intervention.md
          - Stages: reference/services/stages.md
          - Weightings: reference/services/weightings.md
          - Report: reference/services/report.md
          - Data Ingestion: reference/services/data_ingestion.md
  - Architecture:
    - "Design Philosophy": architecture/philosophy.md
    - "Overview": architecture/overview.md
    - "Scoring": architecture/scoring.md
  - About:
    - "Extensions": about/extensions.md
    - "Improvements": about/improvements.md
