site_name: CarbonBalance Docs
theme:
  name: material

markdown_extensions:
- pymdownx.superfences
- pymdownx.details
- pymdownx.tabbed
- admonition
- attr_list
- pymdownx.arithmatex:
    generic: true
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format


extra_javascript:
  - javascripts/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            show_submodules: true
            filters: ["!^_"]
            members_order: source


nav:
  - Home: index.md
  - API:
      - "API Reference": api.md
  - Archtecture:
    - "Design Philosophy": architecture/philosophy.md
    - "Overview": architecture/overview.md
